//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Freeform_Curve.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_FREEFOTYPE                  129
#define IDD_SETTING_DIALOG              130
#define IDC_EDIT_CONTROL_POINT_SIZE     1000
#define IDC_CONTROL_POINT_COLOR         1001
#define IDC_CHECK_TWO_UNIFORM_BSPLINE   1002
#define IDC_CHECK_THREE_UNIFORM_BSPLINE 1003
#define IDC_CHECK_TWO_OPEN_UNIFORM_BSPLINE 1004
#define IDC_CHECK_THREE_OPEN_UNIFORM_BSPLINE 1005
#define IDC_CHECK_FOUR_OPEN_UNIFORM_BSPLINE 1006
#define IDC_CHECK_FOUR_UNIFORM_BSPLINE  1007
#define IDC_EDIT_CURVE_WIDTH            1008
#define IDC_TWO_UNIFORM_BSPLINE_COLOR_WND 1009
#define IDC_TWO_OPEN_UNIFORM_BSPLINE_COLOR_WND 1010
#define IDC_THREE_UNIFORM_BSPLINE_COLOR_WND 1011
#define IDC_THREE_OPEN_UNIFORM_BSPLINE_COLOR_WND 1012
#define IDC_FOUR_UNIFORM_BSPLINE_COLOR_WND 1013
#define IDC_FOUR_OPEN_UNIFORM_BSPLINE_COLOR_WND 1014
#define IDC_CONTROL_POLYGON_COLOR_WND   1015
#define IDC_CHECK_SHOW_CONTROL_POINT    1016
#define IDC_CHECK_SHOW_CONTROL_POLYGON  1017
#define ID_FUNCTION_INPUT               32771
#define ID_FUNCTION_SETTING             32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1017
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
